### ISSUE TITLE
Compiled Binary

### ISSUE THREAD

**Issue by KC5CQW** [pigrew/trueposctrl#3]
Is it possible to include a compiled *.hex in the repository at each commit for direct uploading into the bluepill? 
Update: (I meant *.BIN not *.HEX)

**Comment by pigrew** [comment]
I've manually been posting them.

The latest at [https://github.com/pigrew/trueposctrl/releases](https://github.com/pigrew/trueposctrl/releases) is the latest code. The more recent changes are just to comments, and fix case-sensitivity issues in the build environment.

Unless, you are specifically asking for ".hex" files instead of ".bin" files?

**Comment by KC5CQW** [comment]
Most excellent! I’ve had complete failure to compile the firmware from source. The *.BIN was uploaded inside of two minutes on the first try. I guess my request is best clarified by asking if a link to the above address can be posted on the software wiki page.

**Comment by KC5CQW** [comment]
How about two new releases?: One with SPI and the other with I2C displays enabled. I have a couple of SPI displays I'd like to try before integrating the GPSDO into my distribution amp rack.
Also, I noticed in the code that internal/external DCDC must be selected. Is this for sending Vcc to the display from the STM (internal)? Please explain... FYI, I have probed the TruePosition board for a 5Vdc output and settled on the anode of C3 at U1. Mine is the newer style board from 2010 vintage.

**Comment by pigrew** [comment]
I'm on vacation now, so I can't post any new binaries.

The DCDC converter refers to how the backlight/drive voltage is generated. The display controller has an internal regulator, but one can also use an external one. All of the OLED display boards I've seen use the internal DCDC. It generates the proper voltage from the 3.3V, if I remember correctly.

I ended up buying a larger display 1.3", I think, and implemented that in the code, but I've not posted a build of it either.

**Comment by pigrew** [comment]
Could you mention which display you are using, protocol, size, and chipset? I'll make a second build for it in a few days.

**Comment by KC5CQW** [comment]
Just the standard 0.96” OLED SPI and I2C display versions. Based on your last response on the display feature thread, a release *.bin for each would be fine for those of us not software savvy. Unless there is a protocol detection or some other way to cycle between them that can be coded into the firmware at a later time.
